name: prescription_manager
description: A prescription manager app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  lottie: ^3.3.1

  # Cache
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1

  # State Management
  flutter_riverpod: ^2.6.1

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.5
  firebase_messaging: ^15.2.5

  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.5.3

  # Network
  dio: ^5.8.0+1
  connectivity_plus: ^6.1.4

  # Navigation
  go_router: ^15.1.2

  # Utils
  intl: ^0.20.2
  logger: ^2.5.0
  url_launcher: ^6.3.1
  package_info_plus: ^8.3.0
  device_info_plus: ^11.4.0
  permission_handler: ^12.0.0+1
  path_provider: ^2.1.5
  http: ^1.4.0
  uuid: ^4.5.1
  vibration: ^3.1.3

  # DI
  get_it: ^8.0.3
  injectable: ^2.5.0
  firebase_crashlytics: ^4.3.5
  firebase_analytics: ^11.4.5
  
  # Notifications
  flutter_local_notifications: ^19.2.1

  # Encryption
  flutter_secure_storage: ^9.2.4
  encrypt: ^5.0.3

  # Background processing
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager.git
      path: workmanager
      ref: main
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^5.0.0

  # Testing
  mockito: ^5.4.6

  # Code Generation
  build_runner: ^2.4.15
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.5

  # Assets
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/foreground.png"
  
  # Configuration Android spécifique
  android_adaptive_icon:
    foreground: "assets/icons/foreground.png"
    background: "assets/icons/background.png"
    # monochrome: "assets/icons/monochrome.png"  # Pour Android 13+
  
  # Configuration iOS spécifique
  ios_remove_default_icons: true
  image_path_ios: "assets/icons/foreground.png"
  
  # Web
  # web:
  #   generate: true
  #   image_path: "assets/icons/app_icon.png"
  #   background_color: "#hexcolor"
  #   theme_color: "#hexcolor"

  # Windows
  # windows:
  #   generate: true
  #   image_path: "assets/icons/app_icon.png"
  #   icon_size: 48
  
  # macOS
  # macos:
  #   generate: true
  #   image_path: "assets/icons/app_icon.png"