// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kDebugMode, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4INvhJydvusXwtON_50AhlIZ-U6tUWms',
    appId: '1:221308581892:web:39dd8f63d7b91b7b641d51',
    messagingSenderId: '221308581892',
    projectId: 'prescription-manager-6feca',
    authDomain: 'prescription-manager-6feca.firebaseapp.com',
    storageBucket: 'prescription-manager-6feca.firebasestorage.app',
    measurementId: 'G-5JBC3DMS3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0xiHUvcBveMlfzgtgzLShVWsEyCRm8hA',
    appId: '1:221308581892:android:5d738576bb14aa6c641d51',
    messagingSenderId: '221308581892',
    projectId: 'prescription-manager-6feca',
    storageBucket: 'prescription-manager-6feca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBPZGboyrnmU4RUzQIN-U9TUSjjxoSPLc',
    appId: '1:221308581892:ios:b66094ffcf2b865f641d51',
    messagingSenderId: '221308581892',
    projectId: 'prescription-manager-6feca',
    storageBucket: 'prescription-manager-6feca.firebasestorage.app',
    iosBundleId: 'com.thomassamp.prescriptionManager',
  );

  static void configureEmulators() {
    if (kDebugMode) {
      // Configurer l'émulateur Firestore
      FirebaseFirestore.instance.useFirestoreEmulator('localhost', 8080);

      // Configurer l'émulateur Auth
      FirebaseAuth.instance.useAuthEmulator('localhost', 9099);
    }
  }
}
